apiVersion: skaffold/v2beta6
kind: Config

build:
  artifacts:
    - image: registry.digitalocean.com/learning/k8s-java-hello-world
      sync:
        auto: { }
      jib:
        args: [ "-Psync", "-Djib.from.image=gcr.io/distroless/java:11-debug" ]

deploy:
  kubectl:
    manifests: [ "deploy/kubectl/*.yaml" ]

portForward:
  - resourceType: service
    resourceName: k8s-java-hello-world
    port: 80
  - resourceType: deployment
    resourceName: k8s-java-hello-world
    port: 8090
