apiVersion: skaffold/v2beta24
kind: Config
build:
  artifacts:
  - image: registry.digitalocean.com/october-learning/k8s-java-hello-world
    sync:
      auto: true
    jib:
      args:
      - -Psync
      - -Djib.from.image=gcr.io/distroless/java:11-debug
deploy:
  kubectl:
    manifests:
    - deploy/kubectl/*.yaml

portForward:
- resourceType: deployment
  resourceName: k8s-java-hello-world
  port: 8080
- resourceType: deployment
  resourceName: k8s-java-hello-world
  port: 8090
