namespace: prod

replicaCount: 2

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 1792Mi
  requests:
    cpu: 500m
    memory: 1792Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: relax.integration.kalambagames.com
      paths:
        - /games/url
        - /games/url/launch
        - /users/balance
        - /games/getgames
        - /replay/get
        - /freespins/add
        - /freespins/get
        - /jackpots/values
        - /dictionaries/.*
        - /reconcile

  tls:
    - secretName: k8s-java-hello-world-letsencrypt-prod
      hosts:
        - relax.integration.kalambagames.com

properties:
  baseUrl: "https://iomeu-casino-p2p.api.relaxg.com:7006/p2p/v1"
  kalambaApiUrl: wss://gameserver-api.eu-1.kalambagames.com/oryxreplica/
  launchUrl: https://relax.integration.kalambagames.com/games/url/launch
  resources:
      java: 1024M