kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s-java-hello-world-logging-configuration
  labels:
    app.kubernetes.io/name: k8s-java-hello-world
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: k8s-java-hello-world
data:
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="30 seconds">

      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%-4relative [%thread] %-5level %logger{35} - %msg %n</pattern>
        </encoder>
      </appender>

      <root level="info">
        <appender-ref ref="stdout"/>
      </root>

    </configuration>
