apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-java-hello-world
  labels:
    app.kubernetes.io/name: k8s-java-hello-world
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/part-of: k8s-java-hello-world
imagePullSecrets:
  - name: docker-cfg